Update setup.py
IMPLEMENT FIX FOR THIS ERROR:

pip install git+https://github.com/nathanrchn/perplexityai.git
Collecting git+https://github.com/nathanrchn/perplexityai.git
  Cloning https://github.com/nathanrchn/perplexityai.git to /private/var/folders/_5/xdz2ymlx5hd9n_njml6qn0mh0000gn/T/pip-req-build-2bhcesdy
  Running command git clone --filter=blob:none --quiet https://github.com/nathanrchn/perplexityai.git /private/var/folders/_5/xdz2ymlx5hd9n_njml6qn0mh0000gn/T/pip-req-build-2bhcesdy
  Resolved https://github.com/nathanrchn/perplexityai.git to commit d61c40b109a4614dea12ec91bed580cc64bc791c
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/_5/xdz2ymlx5hd9n_njml6qn0mh0000gn/T/pip-req-build-2bhcesdy/setup.py", line 6, in <module>
          setup(
        File "/opt/anaconda3/lib/python3.11/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/anaconda3/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 147, in setup
          _setup_distribution = dist = klass(attrs)
                                       ^^^^^^^^^^^^
        File "/opt/anaconda3/lib/python3.11/site-packages/setuptools/dist.py", line 303, in __init__
          _Distribution.__init__(self, dist_attrs)
        File "/opt/anaconda3/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 258, in __init__
          getattr(self.metadata, "set_" + key)(val)
        File "/opt/anaconda3/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 1255, in set_requires
          distutils.versionpredicate.VersionPredicate(v)
        File "/opt/anaconda3/lib/python3.11/site-packages/setuptools/_distutils/versionpredicate.py", line 122, in __init__
          raise ValueError("expected parenthesized list: %r" % paren)
      ValueError: expected parenthesized list: '-client'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
felixolszewski@Felixs-MacBook-Pro-3:~/IdeaProjects/AuroraAnalytics/python/scraping scripts$